#!/usr/bin/env python3
"""Read-only native IPC probe through an isolated official CUA MCP launcher.

Never approves permission requests or clicks/types into an application. The
launcher must own its isolated service; this probe stops its process group.
"""
import argparse
import json
import os
from pathlib import Path
import queue
import signal
import subprocess
import threading
import time


def probe(launcher, output, startup_grace=0):
    launcher = launcher.expanduser().resolve(strict=True)
    # Only launch the repository's generated isolated runner.
    if 'buddie_service_pid=' not in launcher.read_text() or 'mktemp -d /tmp/codex-buddie.' not in launcher.read_text():
        raise ValueError('Expected an isolated launcher generated by scripts/prepare.py.')
    proc = subprocess.Popen([str(launcher)], stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True, bufsize=1, start_new_session=True)
    events = queue.Queue()
    logs = []
    report = {'status': 'not-completed', 'observed_at_utc': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
              'scope': 'Official CUA initialization and read-only native app inventory; no UI actions or permission approvals.'}

    def read(stream, kind):
        for line in stream:
            events.put((kind, line))
        events.put((kind, None))

    for stream, kind in [(proc.stdout, 'out'), (proc.stderr, 'err')]:
        threading.Thread(target=read, args=(stream, kind), daemon=True).start()

    def request(identifier, method, params):
        proc.stdin.write(json.dumps({'jsonrpc': '2.0', 'id': identifier, 'method': method, 'params': params}) + '\n')
        proc.stdin.flush()
        deadline = time.monotonic() + 35
        while time.monotonic() < deadline:
            try:
                kind, line = events.get(timeout=max(.01, deadline-time.monotonic()))
            except queue.Empty:
                break
            if kind == 'err':
                if line: logs.append(line)
                continue
            if line is None:
                raise RuntimeError('Isolated CUA process closed its output.')
            message = json.loads(line)
            if message.get('id') == identifier and ('result' in message or 'error' in message):
                if 'error' in message: raise RuntimeError(message['error'].get('message', 'MCP error'))
                return message['result']
            if 'id' in message and 'method' in message:
                raise RuntimeError('Interactive access request received; no permission was approved.')
        raise TimeoutError(f'Timed out waiting for {method}.')

    try:
        request(1, 'initialize', {'protocolVersion': '2025-03-26', 'capabilities': {},
                                 'clientInfo': {'name': 'buddie-local-probe', 'version': '1'}})
        proc.stdin.write(json.dumps({'jsonrpc': '2.0', 'method': 'notifications/initialized'}) + '\n')
        proc.stdin.flush()
        if startup_grace:
            print(f'Isolated CUA initialized; allowing {startup_grace:g}s startup grace (process group {proc.pid}).', flush=True)
            time.sleep(startup_grace)
            if proc.poll() is not None: raise RuntimeError('Isolated CUA exited during startup grace.')
        report['startup_grace_seconds'] = startup_grace
        result = request(2, 'tools/call', {'name': 'js', 'arguments': {
            'code': 'try { var apps = await cua.listApps({emit:false}); nodeRepl.write(JSON.stringify({nativeAppCount:apps.length,errors:[]})); } catch(error) { var causes=[]; for(var cause=error;cause && causes.length<6;cause=cause.cause) causes.push(String(cause)); nodeRepl.write(JSON.stringify({nativeAppCount:0,errors:causes})); }',
            'title': 'Verify isolated Buddie native IPC', 'timeout_ms': 20000}})
        report['tool_error'] = bool(result.get('isError'))
        # Save counts/error descriptions, not a list of the user's applications.
        for item in result.get('content', []):
            if item.get('type') != 'text': continue
            text = item.get('text', '')
            try:
                value = json.loads(text)
                if isinstance(value, dict) and 'nativeAppCount' in value:
                    report.update(value)
            except ValueError:
                if result.get('isError'): report.setdefault('tool_messages', []).append(text[:2000])
        report['status'] = 'pass' if report.get('nativeAppCount', 0)>0 and not report['tool_error'] and not report.get('errors') else 'blocked'
    except Exception as error:
        report['status'] = 'blocked'
        report['error'] = str(error)
    finally:
        try: os.killpg(proc.pid, signal.SIGTERM)
        except ProcessLookupError: pass
        try: proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            os.killpg(proc.pid, signal.SIGKILL); proc.wait()
        while not events.empty():
            kind, line = events.get_nowait()
            if kind == 'err' and line: logs.append(line)
        report['team_not_found_in_log'] = any('teamNotFound' in line for line in logs)
        report['renderer_loaded'] = any('Native cursor renderer shim loaded' in line for line in logs)
        report['saved_appearance_prepared'] = any('Saved cursor appearance prepared' in line for line in logs)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(report, indent=2) + '\n')
        output.with_suffix('.log').write_text(''.join(logs))
    print(json.dumps(report, indent=2), flush=True)
    return 0 if report['status'] == 'pass' else 1


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--launcher', type=Path, required=True)
    parser.add_argument('--report', type=Path, required=True)
    parser.add_argument('--startup-grace', type=float, default=0)
    args = parser.parse_args()
    if not 0 <= args.startup_grace <= 20: parser.error('Startup grace must be between 0 and 20 seconds.')
    raise SystemExit(probe(args.launcher, args.report, args.startup_grace))
